name: 'ESLint'

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 'Install Node.js dependencies'
        run: |
          npm ci

      - name: 'Linting'
        run: npm run lint
