name: 'Prettier'

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Prettify code'
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: '--write src public/index.html --config .prettierrc.json'
          only_changed: False
          dry: False
          github_token: ${{ secrets.GITHUB_TOKEN }}
